server_name: enterprise-nats

port: 4222
http_port: 8222

jetstream {
  store_dir: "/data/jetstream"
  max_mem_store: 1Gb
  max_file_store: 10Gb
}

max_payload: 8Mb
max_connections: 65536

debug: false
trace: false
