function normalizeContinuation(message) {
  return String(message || "").trim().toLocaleLowerCase("it-IT").replace(/[’‘]/g, "'").replace(/[.!?…]+$/u, "").replace(/\s+/g, " ");
}

// Exact requests generated by the UI, never options inferred from model prose.
// Matching one only narrows tools to read-only; it grants no new authority.
const FRESH_READ_REQUESTS = new Set([
  "Controlla lo stato attuale del VPS e segnala solo problemi sostenuti da dati recenti.",
  "Controlla servizi e container infrastrutturali effettivamente presenti.",
  "Controlla gli esiti dei backup e le pianificazioni server-side visibili dagli strumenti.",
  "Controlla nuovamente lo stato attuale del VPS.",
  "Leggi i log recenti del servizio coinvolto e verifica la diagnosi.",
  "Verifica l’esito dell’operazione precedente senza ripeterla.",
  "Controlla l’ultimo esito del backup e distingui dati verificati e dati mancanti.",
  "Verifica la pianificazione dei backup sul server e la prossima esecuzione.",
  "Ricontrolla disponibilità e salute dei servizi e container coinvolti.",
  "Verifica lo stato attuale di rete, DNS e TLS del server.",
  "Verifica le risorse attuali del server e gli eventuali colli di bottiglia.",
  "Leggi l’audit recente relativo all’operazione precedente.",
].map(normalizeContinuation));

export function assistantContinuationKind(message) {
  const normalized = normalizeContinuation(message);
  return normalized === "riassumi" ? "summary" : normalized === "approfondisci" ? "expand" : FRESH_READ_REQUESTS.has(normalized) ? "fresh-read" : null;
}

export function isCanonicalAssistantContinuation(message) {
  return assistantContinuationKind(message) !== null;
}

export function shouldReloadHistoricalAttachmentContext(message, attachmentIds = [], internalAttachmentContinuation = false) {
  if (internalAttachmentContinuation || (Array.isArray(attachmentIds) && attachmentIds.length > 0)) return true;
  return !isCanonicalAssistantContinuation(message);
}
