http:
  middlewares:
    enterprise-security-headers:
      headers:
        browserXssFilter: true
        contentTypeNosniff: true
        frameDeny: true
        referrerPolicy: no-referrer
        forceSTSHeader: true
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        customResponseHeaders:
          X-Permitted-Cross-Domain-Policies: none
          X-Content-Type-Options: nosniff
          Permissions-Policy: "camera=(), microphone=(), geolocation=()"

    keycloak-security-headers:
      headers:
        browserXssFilter: true
        contentTypeNosniff: true
        referrerPolicy: no-referrer
        forceSTSHeader: true
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        customResponseHeaders:
          X-Permitted-Cross-Domain-Policies: none
          X-Content-Type-Options: nosniff
          Permissions-Policy: "camera=(), microphone=(), geolocation=()"

    enterprise-db-admin-frame-headers:
      headers:
        browserXssFilter: true
        contentTypeNosniff: true
        customFrameOptionsValue: SAMEORIGIN
        referrerPolicy: no-referrer
        forceSTSHeader: true
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        customResponseHeaders:
          X-Permitted-Cross-Domain-Policies: none
          X-Content-Type-Options: nosniff
          Permissions-Policy: "camera=(), microphone=(), geolocation=()"

    enterprise-edge-forwarded-https:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: https
          X-Forwarded-Port: "443"

    enterprise-rate-limit:
      rateLimit:
        average: 120
        burst: 60
        period: 1m

    enterprise-compress:
      compress: {}

    enterprise-redirect-https:
      redirectScheme:
        scheme: https
        permanent: true
