http:
  routers:
    enterprise-projects:
      rule: HostRegexp(`^[a-z0-9-]+\.platform-infrastructure\.com$`)
      entryPoints:
        - web
      priority: 50
      middlewares:
        - enterprise-edge-forwarded-https@file
        - enterprise-security-headers@file
        - enterprise-rate-limit@file
        - enterprise-compress@file
      service: enterprise-project-router

  services:
    enterprise-project-router:
      loadBalancer:
        servers:
          - url: http://project-router:8080
