import test from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {EventEmitter} from 'node:events';
import {createNativeAdmissionPayload,signAdmission,verifyAdmissionDocument} from './local-private-backup-admission.mjs';
import {admitGeneration} from './local-private-docker-action-broker.mjs';
import {canonicalJson,sha256} from './docker-action-contract.mjs';
import {exchangeNativeSocket,signNativeRequest,verifyNativeResponse,runNativeOperator} from './backup-native-operator-client.mjs';
const H=x=>x.repeat(64),I=x=>'sha256:'+H(x);
const now=Date.parse('2026-09-28T07:00:00Z');
function fixture(){
 const keys=crypto.generateKeyPairSync('ed25519');
 const options={backupSigningKeySha256:H('1'),brokerImageId:I('1'),catalogCapabilitySha256:H('2'),combinedRenderSha256:H('3'),expiresAt:'2026-10-28T07:00:00.000Z',issuedAt:new Date(now).toISOString(),generation:11,previousAdmissionSha256:H('a'),jobCapabilitySha256:H('4'),offsiteRestoreCapabilitySha256:H('5'),offsiteCapabilitySha256:H('6'),releaseCommitSha1:'a'.repeat(40),schedulerImageId:I('2'),treeSha256:H('7'),nativeOffsite:{backend:'ftps-multipart-v2',host:'92.113.28.106',port:21,tlsName:'hstgr.io',folder:'/server-platform-backups',receiptSchema:'platform.ftps-recovery-point/v2',maxBytes:70000000000,maxAgeSeconds:1209600,maxPoints:6,maxPartBytes:1000000000,restoreSelection:'latest-complete-authenticated',activationEvidence:{manifestId:'manifest-scheduled-platform-20260928-012231-ee83d2',manifestDigest:H('8'),receiptSha256:H('9'),requiredLiveAnchor:false}},objectStore:{backend:'rustfs',container:'gf-rustfs',volume:'platform_rustfs_data',image:'rustfs/rustfs@sha256:'+H('b'),imageId:I('b'),archiveFormat:'rustfs-volume/v1',rootMarker:'.rustfs.sys',restoreMode:'isolated-only'},operator:{protocol:'platform.backup-operator/v2',socket:'/run/platform/backup-operator/operator.sock',uid:0,helperSha256:H('1'),restoreHelperSha256:H('2'),rustfsHelperSha256:H('3'),rustfsRestoreHelperSha256:H('4'),workerSha256:H('5'),peerContainer:'gf-docker-action-broker',peerImageId:I('1')}};
 const payload=createNativeAdmissionPayload(options);const doc=signAdmission(payload,keys.privateKey);return {options,payload,doc,keys};
}
test('native signed contract has no OneDrive live anchor and retains exact fixed endpoint',()=>{const f=fixture();const verified=verifyAdmissionDocument(f.doc,{publicKeyPem:f.keys.publicKey,now});assert.equal(verified.payload.resources.offsite.backend,'ftps-multipart-v2');assert.equal(verified.payload.resources.offsite.activationEvidence.requiredLiveAnchor,false);assert.ok(!canonicalJson(f.doc).includes('platform-onedrive'));});
test('native valid signature cannot widen destination, archive backend, helper, or expiry',()=>{const f=fixture();for(const mutate of [p=>p.resources.offsite.host='other',p=>p.resources.offsite.maxBytes++,p=>p.resources.offsite.activationEvidence.requiredLiveAnchor=true,p=>p.resources.objectStore.rootMarker='.minio.sys',p=>p.resources.objectStore.restoreMode='production',p=>p.resources.operator.socket='/run/docker.sock',p=>p.resources.operator.peerImageId=I('d'),p=>p.resources.operator.workerSha256=H('0'),p=>p.expiresAt='2027-01-01T00:00:00Z']){const p=structuredClone(f.payload);mutate(p);assert.throws(()=>verifyAdmissionDocument(signAdmission(p,f.keys.privateKey),{publicKeyPem:f.keys.publicKey,now}));}});
test('v1/v2 signature domains cannot be relabelled and unsigned mutation denied',()=>{const f=fixture();for(const mutation of [d=>d.schema='platform.local-private-backup-admission/v1',d=>d.payload.resources.offsite.folder='/public_html']){const d=structuredClone(f.doc);mutation(d);assert.throws(()=>verifyAdmissionDocument(d,{publicKeyPem:f.keys.publicKey,now}));}});
test('forward g10 to g11 preserves replay files, denies rollback/gap/substitution',()=>{const f=fixture(),dir=fs.mkdtempSync(path.join(os.tmpdir(),'native-forward-'));try{fs.writeFileSync(path.join(dir,'active-admission.json'),canonicalJson({generation:10,admissionSha256:H('a')})+'\n',{mode:0o600});fs.writeFileSync(path.join(dir,'replay-proof'),'preserve');const trusted={document:f.doc,intent:{generation:11},receipt:f.payload};admitGeneration(dir,trusted);admitGeneration(dir,trusted);assert.equal(fs.readFileSync(path.join(dir,'replay-proof'),'utf8'),'preserve');for(const g of [10,13])assert.throws(()=>admitGeneration(dir,{...trusted,intent:{generation:g}}));assert.throws(()=>admitGeneration(dir,{...trusted,document:{...f.doc,signature:{...f.doc.signature,value:'changed'}}}));assert.equal(JSON.parse(fs.readFileSync(path.join(dir,'active-admission.json'))).admissionSha256,sha256(canonicalJson(f.doc)));}finally{fs.rmSync(dir,{recursive:true,force:true});}});
class Socket extends EventEmitter{destroy(){this.destroyed=true;}write(frame){this.frame=frame;}}
test('Unix client abort before connect opens no socket',async()=>{const c=new AbortController();c.abort();await assert.rejects(exchangeNativeSocket(Buffer.from('x'),{signal:c.signal,connect:()=>{throw Error('must not connect');}}),e=>e.preserveOperation===true);});
test('Unix client deadline closes socket and preserves unresolved operation',async()=>{const s=new Socket();await assert.rejects(exchangeNativeSocket(Buffer.from('x'),{deadlineMs:5,connect:()=>s}),e=>e.preserveOperation===true);assert.equal(s.destroyed,true);assert.equal(s.eventNames().length,0);});
test('Unix client complete canonical response closes and removes listeners',async()=>{const s=new Socket(),p=exchangeNativeSocket(Buffer.from('x'),{connect:()=>s});s.emit('connect');s.emit('data',Buffer.from('{"ok":true}\n'));s.emit('end');assert.deepEqual(await p,{ok:true});assert.equal(s.eventNames().length,0);});
test('Unix client oversize or malformed close preserves operation',async()=>{for(const data of [Buffer.alloc(65537),Buffer.from('bad\n')]){const s=new Socket(),p=exchangeNativeSocket(Buffer.from('x'),{connect:()=>s});s.emit('data',data);if(!s.destroyed)s.emit('end');await assert.rejects(p,e=>e.preserveOperation===true);assert.equal(s.destroyed,true);}});
test('native response selection and exact receipt stay authenticated',()=>{
 const key=Buffer.from('fixture-capability-key'),f=fixture();const request=signNativeRequest({schema:'platform.backup-operator-request/v2',action:'restore.offsite.proof',requestId:H('a'),admissionSha256:sha256(canonicalJson(f.doc)),generation:11,issuedAt:new Date(now).toISOString(),expiresAt:new Date(now+60000).toISOString(),parameters:{}},key);
 const selection={schema:'platform.backup-operator-selection/v2',action:request.payload.action,manifestId:f.payload.resources.offsite.activationEvidence.manifestId,manifestDigest:H('8'),bundle:'backup-'+f.payload.resources.offsite.activationEvidence.manifestId+'.tar.gpg',receiptSha256:H('9')};
 const p={schema:'platform.backup-operator-result/v2',requestSha256:sha256(canonicalJson(request)),admissionSha256:request.payload.admissionSha256,action:request.payload.action,status:'passed',errorCode:null,selection,result:{backend:'ftps-multipart-v2',productionModified:false,manifestId:selection.manifestId,manifestDigest:selection.manifestDigest,artifactCount:69,actualDownloadVerified:true,decryptVerified:true,everyArtifactShaAndHmacVerified:true,rustfsRestoreVerified:true,receiptSha256:selection.receiptSha256,selection}};
 const signed=v=>({payload:v,hmacSha256:crypto.createHmac('sha256',key).update('platform-backup-operator-response-v2\0'+canonicalJson(v)).digest('hex')});
 assert.equal(verifyNativeResponse(signed(p),request,key).artifactCount,69);
 for(const mutate of [v=>v.result.manifestDigest=H('f'),v=>v.result.selection={...selection,receiptSha256:H('f')},v=>v.result.receiptSha256=H('f'),v=>v.result.rustfsRestoreVerified=false,v=>v.result.actualDownloadVerified=false]){const v=structuredClone(p);mutate(v);assert.throws(()=>verifyNativeResponse(signed(v),request,key));}
 const changed=signed(structuredClone(p));changed.payload.selection.manifestId='manifest-other-20260928000000';assert.throws(()=>verifyNativeResponse(changed,request,key),/HMAC/);
});

test('client journal and parent directory are durable before first transport',async()=>{
 const f=fixture(),dir=fs.mkdtempSync(path.join(os.tmpdir(),'native-client-')),events=[],original=fs.fsyncSync;
 const cap=path.join(dir,'cap');fs.writeFileSync(cap,'test-only',{mode:0o600});
 fs.fsyncSync=(fd)=>{events.push(fs.fstatSync(fd).isDirectory()?'dir-fsync':'file-fsync');return original(fd);};
 try{await assert.rejects(runNativeOperator({action:'backup.offsite.sync',requestSha256:H('a'),trusted:{document:f.doc,receipt:f.payload,capabilityFiles:{'backup.offsite.sync':cap}},stateDir:dir,transport:async bytes=>{events.push('transport');assert.ok(fs.existsSync(path.join(dir,'native-operator',H('a')+'.json')));throw Error('fixture transport stop');}}),/fixture transport/);assert.deepEqual(events,['file-fsync','dir-fsync','transport']);}finally{fs.fsyncSync=original;fs.rmSync(dir,{recursive:true,force:true});}
});
