#!/usr/bin/env node
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const workflow = fs.readFileSync(path.join(root, ".github", "workflows", "enterprise-infra.yml"), "utf8");
const producerWorkflow = fs.readFileSync(path.join(root, ".github", "workflows", "release-attestation.yml"), "utf8");
const actionsRuntime = JSON.parse(fs.readFileSync(path.join(root, "governance", "github-actions-runtime.json"), "utf8"));

function workflowJob(source, jobName) {
  const start = source.search(new RegExp(`^  ${jobName}:`, "m"));
  if (start < 0) return "";
  const tail = source.slice(start + 1);
  const next = tail.search(/^  [A-Za-z0-9_-]+:/m);
  return next < 0 ? source.slice(start) : source.slice(start, start + 1 + next);
}

function wiringIssues(source) {
  const issues = [];
  const requireText = (text, label) => { if (!source.includes(text)) issues.push(label); };
  const forbidText = (text, label) => { if (source.includes(text)) issues.push(label); };
  const deploy = workflowJob(source, "deploy-vps");
  for (const input of [
    "release_attestation_run_attempt:",
    "artifact_receipt_sha256:",
  ]) requireText(input, `missing dispatch input ${input}`);
  requireText("Generate current deploy-consumer challenge", "current-run CSPRNG challenge is not generated before provider dispatch");
  requireText("--challengeOutput \"$CHALLENGE_FILE\"", "challenge is not generated by the repository challenge generator");
  requireText('ARTIFACT_NAME="platform-trusted-deployment-admission-${CHALLENGE_NONCE}"', "trusted provider artifact name is not challenge-bound");
  requireText("run-id: ${{ steps.provider.outputs.run_id }}", "trusted provider run identity is not authenticated from the dispatched run");
  requireText("repository: ${{ steps.provider.outputs.repository }}", "trusted provider repository is not policy-bound");
  requireText("inputs[challenge_nonce]=${CHALLENGE_NONCE}", "trusted provider dispatch is not bound to the current challenge");
  requireText("trusted-provider-run-policy.mjs", "trusted producer workflow/ref/run metadata is not authenticated");
  requireText('--metadataSha256 "$TRUSTED_PROVIDER_METADATA_SHA256"', "trusted producer metadata hash is not handed off");
  requireText('--providerRunId "$TRUSTED_PROVIDER_RUN_ID"', "deployment receipt is not bound to provider run ID");
  requireText('--providerRunAttempt "$TRUSTED_PROVIDER_RUN_ATTEMPT"', "deployment receipt is not bound to provider run attempt");
  requireText(".path == \".github/workflows/release-attestation.yml\"", "release producer workflow path is not authenticated");
  requireText(".head_sha == $sha", "release producer commit is not authenticated");
  requireText(".status == \"completed\" and .conclusion == \"success\"", "release producer completion is not authenticated");
  requireText("test \"${#artifact_receipts[@]}\" -eq 1", "artifact receipt cardinality is not exact");
  requireText("test \"${#deployment_receipts[@]}\" -eq 1", "deployment receipt cardinality is not exact");
  requireText("test \"${#source_archives[@]}\" -eq 1", "source archive cardinality is not exact");
  requireText("'.sourceArchiveSha256' \"${artifact_receipts[0]}\"", "artifact receipt is not bound to the selected source archive");
  requireText("'.sourceArchiveSha256' \"${deployment_receipts[0]}\"", "deployment receipt is not bound to the selected source archive");
  requireText("= \"$EXPECTED_ARTIFACT_RECEIPT_SHA256\"", "artifact receipt hash is not checked after download");
  requireText('DEPLOYMENT_RECEIPT_SHA256="$(sha256sum "${deployment_receipts[0]}"', "deployment receipt hash is not computed from the exact downloaded receipt");
  requireText('RUNTIME_INTENT_SHA256="$(jq -er \'.runtimeIntentSha256', "runtime intent hash is not sourced from the authenticated deployment receipt");
  requireText("runtime-intent-policy.mjs --hash", "embedded runtime intent is not independently canonical-hashed");
  requireText('staging_receipts[0]}\")" = "$RUNTIME_INTENT_SHA256"', "staging receipt is not required to match the authenticated runtime intent");
  requireText("--artifactVerificationOnly", "artifact-only cryptographic gate is absent");
  requireText('--sourceArchive "$RELEASE_SOURCE_ARCHIVE"', "fresh artifact verification does not consume the exact source archive");
  requireText('--receiptOutput "$REVERIFIED_ARTIFACT_RECEIPT"', "fresh cryptographic output is not captured");
  requireText('sha256sum "$REVERIFIED_ARTIFACT_RECEIPT"', "fresh cryptographic output hash is not checked");
  requireText('cmp -- "$REVERIFIED_ARTIFACT_RECEIPT" "$ARTIFACT_RECEIPT"', "downloaded receipt is not byte-equal to fresh verification output");
  requireText('--artifactReceipt "$REVERIFIED_ARTIFACT_RECEIPT"', "deployment policy does not consume the fresh cryptographic output");
  requireText('--sourceArchiveSha256 "$RELEASE_SOURCE_ARCHIVE_SHA256"', "deployment policy is not bound to the exact source archive");
  requireText('exact-source-archive.tar"', "admitted handoff does not preserve the verified source archive");
  const policyCalls = source.match(/node \.\/scripts\/deployment-receipt-policy\.mjs/g) ?? [];
  if (policyCalls.length !== 2) issues.push("trusted receipt policy must run before upload and again before deploy");
  requireText("name: admitted-deployment-receipts-${{ github.run_id }}", "validated receipt handoff artifact is not run-bound");
  requireText("needs:\n      - enterprise-readiness\n      - release-admission\n    if: github.event_name == 'workflow_dispatch'", "DAST does not require the exact admitted release candidate");
  requireText('--scanRequestOutput "$DAST_SCAN_REQUEST"', "DAST candidate does not emit one non-authorizing scan request");
  requireText("inputs[mode]=dast-countersign", "DAST authorization is not delegated to the independent provider");
  requireText('--dastAttestationBundle "$DAST_BUNDLE"', "DAST provider receipt is not verified with its Sigstore bundle");
  requireText('--challengeNonce "$CHALLENGE_NONCE"', "DAST receipt does not carry a fresh challenge");
  requireText('test "$DAST_TARGET" = "$CANONICAL_TARGET"', "DAST receipt is not bound to the exact protected-environment target");
  requireText("name: dast-verification-${{ github.run_id }}", "DAST provider evidence artifact is not run-bound");
  requireText("path: ${{ runner.temp }}/dast-verification/", "DAST provider evidence handoff path is not exact");
  requireText("needs:\n      - enterprise-readiness\n      - release-admission\n      - dast-zap", "deploy DAG does not require readiness, admission and DAST");
  requireText("test \"$(jq -er '.status' governance/activation-promotion.json)\" = READY", "external activation promotion policy does not fail closed");
  requireText("test \"$(jq -er '.trustedProducer.artifactName' governance/activation-promotion.json)\" = platform-promoted-activation", "activation promotion artifact name is not fixed");
  requireText("ACTIVATION_PROMOTION_READ_TOKEN", "trusted promoter read token is not isolated in the production environment");
  requireText("ACTIVATION_PROMOTION_RUN_ID", "trusted promoter run ID is not provider-selected");
  requireText("ACTIVATION_PROMOTION_RUN_ATTEMPT", "trusted promoter run attempt is not provider-selected");
  if ((source.match(/Install checksum-pinned GitHub attestation verifier/g) ?? []).length < 2) {
    issues.push("deploy job does not install the pinned verifier before promoter authentication");
  }
  requireText("node ./scripts/activation-promotion-policy.mjs", "trusted post-DAST promotion policy is not executed");
  for (const argument of [
    '--releaseBundle "$PROMOTED/release-activation.bundle"',
    '--releaseBundleManifest "$PROMOTED/release-activation-bundle-manifest.json"',
    '--dockerActivationEnvelope "$PROMOTED/docker-runtime-activation.dsse.json"',
    '--dastAuthorization "$PROMOTED/dast-activation-authorization.json"',
    '--dastProviderReceipt "$DAST_RECEIPT"',
    '--dastProviderMetadata "$DAST_PROVIDER_METADATA"',
    '--dastProviderAttestationBundle "$DAST_PROVIDER_ATTESTATION_BUNDLE"',
  ]) requireText(argument, `activation promotion v2 is missing ${argument}`);
  requireText("node scripts/activation-receipt-policy.test.mjs", "integrated CI does not replay the authoritative Docker active-receipt contract");
  requireText('--activationAdmission "$PROMOTED/activation-admission.jsonl"', "activation DSSE admission sidecar is not verified");
  requireText('--trustedRoot "$PROMOTED/sigstore-trusted-root.json"', "activation promotion does not use the policy-pinned trusted root");
  requireText('test "$(find "$PROMOTED" -mindepth 1 -maxdepth 1 -type f | wc -l | tr -d \' \')" -eq 7', "promoted activation artifact cardinality is not exact");
  requireText("release-activation.bundle release-activation-bundle-manifest.json docker-runtime-activation.dsse.json dast-activation-authorization.json activation-admission.jsonl sigstore-trusted-root.json activation-promotion-receipt.json", "promoted activation flat file set is not exact v2");
  requireText('test "$(wc -c < "$RESULT" | tr -d \' \')" -le 1048576', "promotion result is not bounded before use");
  requireText('test "$(jq -er \'.dastChainSha256\' "$RESULT")" = "$(jq -er \'.chainSha256\' "$PROMOTED/dast-activation-authorization.json")"', "promotion result is not bound to the validated authorization chain");
  const explicitlyExported = new Set(
    [...deploy.matchAll(/^\s*export\s+([A-Z][A-Z0-9_]*(?:\s+[A-Z][A-Z0-9_]*)*)\s*$/gm)]
      .flatMap((match) => match[1].split(/\s+/)),
  );
  for (const variable of [
    "DEPLOY_ARTIFACT_RECEIPT_PATH:",
    "DEPLOY_ARTIFACT_RECEIPT_SHA256:",
    "DEPLOY_ADMISSION_RECEIPT_PATH:",
    "DEPLOY_ADMISSION_RECEIPT_SHA256:",
    "DEPLOY_TRUSTED_PROVIDER_METADATA_PATH:",
    "DEPLOY_TRUSTED_PROVIDER_METADATA_SHA256:",
    "DEPLOY_TRUSTED_PROVIDER_RUN_ID:",
    "DEPLOY_TRUSTED_PROVIDER_RUN_ATTEMPT:",
    "DEPLOY_DAST_PROVIDER_RECEIPT_PATH:",
    "DEPLOY_DAST_ACTIVATION_AUTHORIZATION_PATH:",
    "DEPLOY_RELEASE_BUNDLE_MANIFEST_PATH:",
    "DEPLOY_ACTIVATION_PROMOTION_RESULT:",
  ]) requireText(variable, `deploy consumer is missing ${variable}`);
  for (const variable of [
    "DEPLOY_ENVIRONMENT_SHA256",
    "DEPLOY_DAST_PROVIDER_RECEIPT_SHA256",
    "DEPLOY_DAST_ACTIVATION_AUTHORIZATION_SHA256",
    "DEPLOY_DAST_CHAIN_SHA256",
    "DEPLOY_DAST_PROVIDER_METADATA_SHA256",
    "DEPLOY_DAST_SIGSTORE_BUNDLE_SHA256",
    "DEPLOY_DAST_SIGSTORE_SUBJECT",
    "DEPLOY_RELEASE_BUNDLE_SHA256",
    "DEPLOY_RELEASE_BUNDLE_SIZE_BYTES",
    "DEPLOY_RELEASE_BUNDLE_MANIFEST_SHA256",
    "DEPLOY_DOCKER_ACTIVATION_ENVELOPE_SHA256",
    "DEPLOY_DOCKER_ACTIVATION_ENVELOPE_SIZE_BYTES",
    "DEPLOY_DOCKER_ACTIVATION_ENVELOPE_PAYLOAD_TYPE",
    "DEPLOY_DOCKER_ACTIVATION_RUNTIME_INTENT_ID",
    "DEPLOY_DOCKER_ACTIVATION_GENERATION",
  ]) {
    if (!new RegExp(`^\\s*${variable}=`, "m").test(deploy) || !explicitlyExported.has(variable)) {
      issues.push(`trusted ops input ${variable} is not assigned and exported to the isolated runner`);
    }
  }
  requireText("OPS_RESULT=\"$(sh ./scripts/ops-image-trust.sh)\"", "ops image is not checked against the provider receipt");
  requireText("docker run --rm --read-only --cap-drop ALL --security-opt no-new-privileges", "trusted ops runner lacks the fixed container hardening boundary");
  requireText('"$OPS_IMAGE_ID" deploy-vps', "production mutation does not use the admitted ops image entrypoint");
  requireText('"$OPS_IMAGE_ID" deploy-vps > "$ACTIVATION_RECEIPT"', "activation receipt is not captured outside the container without log disclosure");
  requireText("name: activation-receipt-${{ github.run_id }}", "activation receipt evidence artifact is not run-bound");
  requireText("path: ${{ runner.temp }}/activation-receipt.json", "activation receipt evidence path is not exact");
  forbidText("run: sh ./scripts/deploy-vps.sh", "candidate checkout remains a production mutation sink");
  if (deploy.includes("docker.sock")) {
    issues.push("trusted ops runner receives the Docker control socket");
  }
  if ((source.match(/^\s+"\$OPS_IMAGE_ID" deploy-vps > "\$ACTIVATION_RECEIPT"\s*$/gm) ?? []).length !== 1) {
    issues.push("trusted ops image entrypoint sink cardinality is not exact");
  }
  const expectedMounts = [
    '"$HOME/.ssh/deploy_key:/run/platform-deploy/ssh-key:ro"',
    '"$HOME/.ssh/known_hosts:/run/platform-deploy/known-hosts:ro"',
    '"$DEPLOY_ARTIFACT_RECEIPT_PATH:/run/platform-deploy/artifact-verification.json:ro"',
    '"$DEPLOY_ADMISSION_RECEIPT_PATH:/run/platform-deploy/trusted-deployment-admission.json:ro"',
    '"$DEPLOY_TRUSTED_PROVIDER_METADATA_PATH:/run/platform-deploy/trusted-provider-run.json:ro"',
    '"$DEPLOY_DAST_PROVIDER_RECEIPT_PATH:/run/platform-deploy/dast-provider-verification.json:ro"',
    '"$DEPLOY_DAST_ACTIVATION_AUTHORIZATION_PATH:/run/platform-deploy/dast-activation-authorization.json:ro"',
    '"$DEPLOY_RELEASE_BUNDLE_MANIFEST_PATH:/run/platform-deploy/release-activation-bundle-manifest.json:ro"',
  ].sort();
  const mounts = [...deploy.matchAll(/^\s+-v\s+(.+?)\s+\\\s*$/gm)].map((match) => match[1]).sort();
  if (JSON.stringify(mounts) !== JSON.stringify(expectedMounts)) {
    issues.push("trusted ops runner mount allowlist is not exact");
  }
  const expectedEnvironment = [
    "DEPLOY_REMOTE", "DEPLOY_SSH_PORT", "DEPLOY_REPO", "DEPLOY_RELEASE_SHA", "DEPLOY_RELEASE_TREE",
    "DEPLOY_ARTIFACT_RECEIPT_SHA256", "DEPLOY_ADMISSION_RECEIPT_SHA256",
    "DEPLOY_TRUSTED_PROVIDER_METADATA_SHA256", "DEPLOY_TRUSTED_PROVIDER_RUN_ID", "DEPLOY_TRUSTED_PROVIDER_RUN_ATTEMPT",
    "DEPLOY_DAST_PROVIDER_RECEIPT_SHA256", "DEPLOY_DAST_ACTIVATION_AUTHORIZATION_SHA256", "DEPLOY_DAST_CHAIN_SHA256",
    "DEPLOY_DAST_PROVIDER_METADATA_SHA256", "DEPLOY_DAST_SIGSTORE_BUNDLE_SHA256", "DEPLOY_DAST_SIGSTORE_SUBJECT",
    "DEPLOY_ENVIRONMENT_SHA256",
    "DEPLOY_RELEASE_BUNDLE_SHA256", "DEPLOY_RELEASE_BUNDLE_SIZE_BYTES", "DEPLOY_RELEASE_BUNDLE_MANIFEST_SHA256",
    "DEPLOY_DOCKER_ACTIVATION_ENVELOPE_SHA256", "DEPLOY_DOCKER_ACTIVATION_ENVELOPE_SIZE_BYTES",
    "DEPLOY_DOCKER_ACTIVATION_ENVELOPE_PAYLOAD_TYPE", "DEPLOY_DOCKER_ACTIVATION_RUNTIME_INTENT_ID", "DEPLOY_DOCKER_ACTIVATION_GENERATION",
    "DEPLOY_CONSUMER_RUN_ID", "DEPLOY_CONSUMER_RUN_ATTEMPT",
    "DEPLOY_ARTIFACT_RECEIPT_PATH", "DEPLOY_ADMISSION_RECEIPT_PATH", "DEPLOY_TRUSTED_PROVIDER_METADATA_PATH",
    "DEPLOY_DAST_PROVIDER_RECEIPT_PATH", "DEPLOY_DAST_ACTIVATION_AUTHORIZATION_PATH", "DEPLOY_RELEASE_BUNDLE_MANIFEST_PATH",
  ].sort();
  const environment = [...deploy.matchAll(/-e\s+([A-Z][A-Z0-9_]*)/g)].map((match) => match[1]).sort();
  if (JSON.stringify(environment) !== JSON.stringify(expectedEnvironment)) {
    issues.push("trusted ops runner environment allowlist is not exact");
  }
  if (/continue-on-error:\s*true|--entrypoint|--privileged|--cap-add|--pid(?:=|\s)|--userns|--env-file/.test(deploy)) {
    issues.push("trusted ops runner admits a forbidden bypass flag");
  }
  if (/\$PWD|github\.workspace|\/opt\/platform-infrastructure/.test(mounts.join("\n"))) {
    issues.push("candidate workspace or code is mounted over the admitted ops image");
  }
  if (/DEPLOY_(?:ACTIVATION_BUNDLE|ACTIVATION_ADMISSION|DAST_RECEIPT|DAST_SCAN_REQUEST|DAST_ATTESTATION_BUNDLE|GH_VERIFIER_ARCHIVE)/.test(deploy)) {
    issues.push("deploy sink retains a legacy generic activation or raw DAST transport name");
  }
  for (const binding of [
    "test \"$(jq -er '.schema' \"$ACTIVATION_RECEIPT\")\" = platform-activation-receipt/v3",
    "test \"$(jq -er '.releaseBundleSha256' \"$ACTIVATION_RECEIPT\")\" = \"$DEPLOY_RELEASE_BUNDLE_SHA256\"",
    "test \"$(jq -er '.dockerActivationEnvelopeSha256' \"$ACTIVATION_RECEIPT\")\" = \"$DEPLOY_DOCKER_ACTIVATION_ENVELOPE_SHA256\"",
    "test \"$(jq -er '.dastAuthorizationSha256' \"$ACTIVATION_RECEIPT\")\" = \"$DEPLOY_DAST_ACTIVATION_AUTHORIZATION_SHA256\"",
    "test \"$(jq -er '.dastChainSha256' \"$ACTIVATION_RECEIPT\")\" = \"$DEPLOY_DAST_CHAIN_SHA256\"",
  ]) requireText(binding, `activation receipt v3 is missing ${binding}`);
  const ordered = [
    "node ./scripts/activation-promotion-policy.mjs",
    "node ./scripts/deployment-receipt-policy.mjs",
    "node ./scripts/dast-runtime-receipt-policy.mjs",
    "- name: Install SSH key",
    'OPS_RESULT="$(sh ./scripts/ops-image-trust.sh)"',
    'OPS_IMAGE_ID="$(printf',
    '"$OPS_IMAGE_ID" deploy-vps > "$ACTIVATION_RECEIPT"',
  ].map((needle) => deploy.indexOf(needle));
  if (ordered.some((index) => index < 0) || ordered.some((index, position) => position > 0 && index <= ordered[position - 1])) {
    issues.push("promotion, receipt revalidation, ops trust and activation sink are not causally ordered");
  }
  return issues;
}

assert.deepEqual(wiringIssues(workflow), []);
assert.notDeepEqual(wiringIssues(workflow.replace("DEPLOY_ADMISSION_RECEIPT_SHA256:", "REMOVED_ADMISSION_SHA:")), []);
assert.notDeepEqual(wiringIssues(workflow.replace('ARTIFACT_NAME="platform-trusted-deployment-admission-${CHALLENGE_NONCE}"', 'ARTIFACT_NAME="caller-selected-artifact"')), []);
assert.notDeepEqual(wiringIssues(workflow.replace("--challengeOutput \"$CHALLENGE_FILE\"", "--challengeNonce caller-controlled")), []);
assert.notDeepEqual(wiringIssues(workflow.replace("test \"${#deployment_receipts[@]}\" -eq 1", "test \"${#deployment_receipts[@]}\" -ge 1")), []);
assert.notDeepEqual(wiringIssues(workflow.replace("test \"${#source_archives[@]}\" -eq 1", "test \"${#source_archives[@]}\" -ge 1")), []);
assert.notDeepEqual(wiringIssues(workflow.replace("--artifactVerificationOnly", "--skipDeploymentAdmission")), []);
assert.notDeepEqual(wiringIssues(workflow.replace('--sourceArchive "$RELEASE_SOURCE_ARCHIVE"', "--sourceArchive /tmp/caller-selected.tar")), []);
assert.notDeepEqual(wiringIssues(workflow.replace('cmp -- "$REVERIFIED_ARTIFACT_RECEIPT" "$ARTIFACT_RECEIPT"', "true")), []);
assert.notDeepEqual(wiringIssues(workflow.replace("repository: ${{ steps.provider.outputs.repository }}", "repository: owner/caller-selected")), []);
assert.notDeepEqual(wiringIssues(workflow.replaceAll('--providerRunAttempt "$TRUSTED_PROVIDER_RUN_ATTEMPT"', '--providerRunAttempt "1"')), []);
assert.notDeepEqual(wiringIssues(workflow.replace("runtime-intent-policy.mjs --hash", "printf unverified-runtime-hash")), []);
assert.notDeepEqual(wiringIssues(workflow.replaceAll("DEPLOY_TRUSTED_PROVIDER_METADATA_PATH:", "REMOVED_PROVIDER_METADATA_PATH:")), []);
assert.notDeepEqual(wiringIssues(workflow.replaceAll("DEPLOY_DAST_PROVIDER_RECEIPT_PATH:", "REMOVED_DAST_PATH:")), []);
assert.notDeepEqual(wiringIssues(workflow.replaceAll("DEPLOY_DAST_ACTIVATION_AUTHORIZATION_PATH:", "REMOVED_DAST_AUTHORIZATION_PATH:")), []);
assert.notDeepEqual(wiringIssues(workflow.replaceAll("ACTIVATION_PROMOTION_READ_TOKEN", "CALLER_TOKEN")), []);
assert.notDeepEqual(wiringIssues(workflow.replaceAll("Install checksum-pinned GitHub attestation verifier", "Removed verifier install")), []);
assert.notDeepEqual(wiringIssues(workflow.replace('"$OPS_IMAGE_ID" deploy-vps', '"$OPS_IMAGE_ID" attacker-selected')), []);
const trustedOpsRunAnchor = "docker run --rm --read-only --cap-drop ALL --security-opt no-new-privileges";
assert.equal(workflow.split(trustedOpsRunAnchor).length - 1, 1);
assert.notDeepEqual(wiringIssues(workflow.replace(
  trustedOpsRunAnchor,
  "docker run --rm -v /var/run/docker.sock:/var/run/docker.sock --read-only --cap-drop ALL --security-opt no-new-privileges",
)), []);
assert.notDeepEqual(wiringIssues(workflow.replace(
  "export DEPLOY_ENVIRONMENT_SHA256 DEPLOY_DAST_PROVIDER_RECEIPT_SHA256",
  "export DEPLOY_DAST_PROVIDER_RECEIPT_SHA256",
)), []);
assert.notDeepEqual(wiringIssues(workflow.replace(
  "          DEPLOY_ENVIRONMENT_SHA256=\"$(jq -er '.runtimeIntent.environmentSha256' \"$DEPLOY_ADMISSION_RECEIPT_PATH\")\"",
  "          true",
)), []);
assert.notDeepEqual(wiringIssues(workflow.replace("platform-promoted-activation", "caller-selected-activation")), []);
assert.notDeepEqual(wiringIssues(workflow.replace(
  'test "$(find "$PROMOTED" -mindepth 1 -maxdepth 1 -type f | wc -l | tr -d \' \')" -eq 7',
  'test "$(find "$PROMOTED" -mindepth 1 -maxdepth 1 -type f | wc -l | tr -d \' \')" -eq 8',
)), []);
assert.notDeepEqual(wiringIssues(workflow.replace("release-activation.bundle release-activation-bundle-manifest.json", "activation.bundle activation-bundle-manifest.json")), []);
assert.notDeepEqual(wiringIssues(workflow.replace('            -v "$HOME/.ssh/deploy_key:', '            -v "$PWD:/opt/platform-infrastructure" \\\n            -v "$HOME/.ssh/deploy_key:')), []);
assert.notDeepEqual(wiringIssues(workflow.replace(
  "docker run --rm --read-only --cap-drop ALL --security-opt no-new-privileges",
  "docker run --rm --privileged --read-only --cap-drop ALL --security-opt no-new-privileges",
)), []);
assert.notDeepEqual(wiringIssues(workflow.replace('"$OPS_IMAGE_ID" deploy-vps > "$ACTIVATION_RECEIPT"', '"$OPS_IMAGE_ID" deploy-vps')), []);
assert.notDeepEqual(wiringIssues(workflow.replace(
  '"$OPS_IMAGE_ID" deploy-vps > "$ACTIVATION_RECEIPT"',
  'true\n          "$OPS_IMAGE_ID" deploy-vps > "$ACTIVATION_RECEIPT"',
).replace(
  "          test -z \"$(find \"$PROMOTED\"",
  '          "$OPS_IMAGE_ID" deploy-vps > "$ACTIVATION_RECEIPT"\n          test -z "$(find "$PROMOTED"',
)), []);

const manifestAttestation = producerWorkflow.indexOf("- name: Attest release subject manifest provenance");
const finalizedReceipt = producerWorkflow.indexOf('--receiptOutput "reports/release/release-artifact-admission-${GITHUB_RUN_ID}.json"');
assert.ok(manifestAttestation >= 0 && finalizedReceipt > manifestAttestation,
  "producer must finalize the artifact receipt only after manifest attestation");
assert.doesNotMatch(
  producerWorkflow.slice(0, manifestAttestation),
  /--receipt(?:Output)?\s+"reports\/release\/release-artifact-admission-/,
  "pre-attestation generation must not mint an artifact receipt",
);
const schedulerProducerBindings = [
  "file: docker/backup-scheduler.Dockerfile",
  "subject-name: ${{ env.PLATFORM_BACKUP_SCHEDULER_IMAGE_REPOSITORY }}",
  "subject-digest: ${{ steps.backup-scheduler.outputs.digest }}",
  '--image "PLATFORM_BACKUP_SCHEDULER_IMAGE=${PLATFORM_BACKUP_SCHEDULER_IMAGE_REPOSITORY}@${PLATFORM_BACKUP_SCHEDULER_DIGEST}"',
  '--buildkitSbom "PLATFORM_BACKUP_SCHEDULER_IMAGE=reports/release/buildkit-sbom-PLATFORM_BACKUP_SCHEDULER_IMAGE-${GITHUB_RUN_ID}.spdx.json"',
  '--registryDescriptor "PLATFORM_BACKUP_SCHEDULER_IMAGE=reports/release/registry-descriptor-PLATFORM_BACKUP_SCHEDULER_IMAGE-${GITHUB_RUN_ID}.json"',
  '--registryResolution "PLATFORM_BACKUP_SCHEDULER_IMAGE=reports/release/registry-resolution-PLATFORM_BACKUP_SCHEDULER_IMAGE-${GITHUB_RUN_ID}.json"',
  'platform-manifest-${key}-${GITHUB_RUN_ID}-linux-amd64.json',
  '--platformManifest "linux/amd64=$platform_manifest"',
];
assert.ok(schedulerProducerBindings.every((binding) => producerWorkflow.includes(binding)),
  "release producer does not attest the dedicated scheduler image through every evidence layer");
assert.ok(!schedulerProducerBindings.every((binding) => producerWorkflow
  .replace("file: docker/backup-scheduler.Dockerfile", "file: docker/ops.Dockerfile").includes(binding)),
"scheduler producer mutation was not detected");
const productionRuntime = actionsRuntime.environments.find((environment) => environment.name === "production");
const productionSecretNames = new Set(productionRuntime?.required_secrets?.map((item) => item.name) ?? []);
const productionVariableNames = new Set(productionRuntime?.required_variables?.map((item) => item.name) ?? []);
assert.ok(["DEPLOY_SSH_KEY", "DEPLOY_SSH_HOST_KEY", "ACTIVATION_PROMOTION_READ_TOKEN"]
  .every((name) => productionSecretNames.has(name)), "production runtime policy omits a trusted deploy secret");
assert.ok(["DEPLOY_REMOTE", "DEPLOY_SSH_PORT", "ACTIVATION_PROMOTION_RUN_ID", "ACTIVATION_PROMOTION_RUN_ATTEMPT"]
  .every((name) => productionVariableNames.has(name)), "production runtime policy omits a trusted deploy variable");

process.stdout.write("trusted receipt workflow wiring tests passed 28/28; provider channel remains EXTERNAL-PENDING\n");
